export enum PermissionEnum {
  MANAGE_ADMINS = 'MANAGE_ADMINS',
  MANAGE_ORDERS = 'MANAGE_ORDERS',
  MANAGE_LOCATIONS = 'MANAGE_LOCATIONS',
  MANAGE_REVIEWS = 'MANAGE_REVIEWS',
  MANAGE_INVOICES = 'MANAGE_INVOICES',
  MANAGE_BLOG = 'MANAGE_BLOG',
  MANAGE_QUOTES = 'MANAGE_QUOTES',
}
